config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles import views

from home import views as home_views


urlpatterns = [
    url(r'',
        home_views.HomePageView.as_view(),
        name='home'
    ),
    url(r'^admin/', include(admin.site.urls)),
]


if settings.DEBUG:
    urlpatterns = [
        url(r'^static/(?P<path>.*)$', views.serve),
    ] + urlpatterns

apps/chat/models.py
from django.db import models
from django_extensions.db import models as dj_extensions_models


class ChatMessage(dj_extensions_models.TimeStampedModel):
    username = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()


class UserEvent(dj_extensions_models.TimeStampedModel):
    user_name = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.conf import settings
from django.views import generic

from chat import models
from home.utils import get_silly_name


class HomePageView(generic.ListView):
    template_name = 'landing/home.html'
    model = models.ChatMessage
    ordering = 'created'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        silly_name = self.request.session.setdefault(
            'silly_name', get_silly_name()
        )
        context['silly_name'] = silly_name
        context['ws_server_path'] = 'ws://{}:{}/'.format(
            settings.CHAT_WS_SERVER_HOST,
            settings.CHAT_WS_SERVER_PORT,
        )
        return context

templates/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css" media="all">
        <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css" media="all">
        <title>{% block title %}{% endblock %}</title>

        {% block extra_css %}{% endblock %}
    </head>

    <body>
        {% block content %}{% endblock %}

        <script src="{% static "js/jquery.min.js" %}" type="text/javascript"></script>
        <script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>
        <script src="{% static "js/handlebars-v1.3.0.js" %}" type="text/javascript"></script>
        {% block extra_js %}{% endblock %}
    </body>

</html>

templates/landing/home.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="messages-container">
                <div id="messages" class="messages">
                    {% for msg in chatmessage_list %}
                    <p>
                        <span class="username">{{ msg.username }}:</span>
                        {{ msg.message }}
                        <span class="timestamp">&ndash; <span data-livestamp="{{ msg.created}}">{{ msg.created }}</span></span>
                    </p>
                    {% endfor %}
                </div>

                <ul id="user-list" class="user-list">
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="add-message">
                <p class="pull-left">Logged in as: <b id="username">{{ silly_name }}</b></p>
                <div class="form-group">
                    <textarea id="chat-message" class="form-control message" placeholder="Write a message"></textarea>
                </div>

                <div class="form-group clearfix">
                    <input id="btn-send-message" type="submit" class="btn btn-primary pull-right send-message" style="margin-left: 10px;" value="Send message" />
                </div>
            </div>
        </div>
    </div>

    <input id="ws-server-path" type="hidden" value="{{ ws_server_path }}">

    {% verbatim %}
    <script id="chat-message-template" type="text/x-handlebars-template">
        <p>
            <span class="username">{{ msg.username }}:</span>
            {{ msg.message }}
            <span class="timestamp">&ndash; <span data-livestamp="{{ msg.created}}">{{ msg.created }}</span></span>
        </p>
    </script>

    <script id="user-list-item-template" type="text/x-handlebars-template">
        <li>{{ username }}</li>
    </script>
    {% endverbatim %}

{% endblock %}

{% block extra_js %}
    <script src="{% static "js/sillyname.js" %}" type="text/javascript"></script>
    <script src="{% static "js/app.js" %}" type="text/javascript"></script>
{% endblock %}